trigger:
- main

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: |
        echo "Building Hello World Java Project"
        javac HelloWorld.java
        jar cfm HelloWorld.jar Manifest.txt HelloWorld.class
        ls
        pwd
        java -jar HelloWorld.jar
      displayName: 'Build Hello World Java Project'
      
- stage: Deploy
  jobs:
  - job: DeployJob
    steps:
    - script: |
        echo 'Executing the Hello World'
        ls 
        pwd 
        java -jar HelloWorld.jar
      displayName: 'Execute Hello World App'
