trigger:
- main  # Define the branch trigger for your pipeline

jobs:
- job: BuildAndRunJava
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        javac HelloWorld.java
        jar cfm HelloWorld.jar Manifest.txt HelloWorld.class
        ls
        pwd

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: 'echo "I’m on stage 2"'
    
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: 'java -jar HelloWorld.jar'
