trigger:
- main  # Define the branch trigger for your pipeline

pool:
  vmImage: 'windows-latest'  # Use an appropriate agent pool and image

jobs:
- job: BuildAndRunJava
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        javac HelloWorld.java
        jar cfm HelloWorld.jar Manifest.txt HelloWorld.class
        pwd

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: 'echo "I’m on stage 2"'

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: 'java -jar HelloWorld.jar'
