trigger:
- main

stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        javac HelloWorld.java
        jar cfm HelloWorld.jar Manifest.txt HelloWorld.class
        sh 'ls'
      displayName: 'Build Hello World Java Project'
  
- stage: Verify
  - script: |
      echo 'Listing files in the directory'
      sh 'ls'
    displayName: 'Verify Jar File'

- stage: Deploy
  - script: |
      echo 'Executing the Hello World '
      java -jar HelloWorld.jar
    displayName: 'Execute Hello World App'
