trigger:
- main

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: |
        echo "Building Hello World Java Project"
        javac HelloWorld.java
        jar cfm HelloWorld.jar Manifest.txt HelloWorld.class
        ls
        pwd
      displayName: 'Build Hello World Java Project'
    
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        artifact: 'HelloWorld'
        publishLocation: 'pipeline'

- stage: Execute
  jobs:
  - job: ExecuteJob
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'specific'
        project: '1646f920-5daa-4584-b42c-cc2684022daa'
        definition: '7'
        buildVersionToDownload: 'latest'
        artifactName: 'HelloWorld'
        targetPath: '$(Pipeline.Workspace)'
    - script: |
        echo 'Executing the Hello World'
        ls 
        pwd 
        java -jar HelloWorld.jar
      displayName: 'Execute Hello World App'
