trigger:
- main

stages:
- stage: BuildandRun
  jobs:
  - job: BuildandRunJob
    steps:
    - script: |
        echo "Building Hello World Java Project"
        javac HelloWorld.java
        jar cfm HelloWorld.jar Manifest.txt HelloWorld.class
        ls
        pwd
        java -jar HelloWorld.jar
        displayName: 'Build Hello World Java Project'

- stage: Execute
  jobs:
  - job: ExecuteJob   
    - script: |
        echo 'Executing the Hello World'
        ls 
        pwd 
        java -jar HelloWorld.jar
      displayName: 'Execute Hello World App'
      
