trigger:
- main

stages:
- stage: Build
  steps:
  - script: |
        echo "Building Hello World Java Project"
        javac HelloWorld.java
        jar cfm HelloWorld.jar Manifest.txt HelloWorld.class
        ls
        pwd
        displayName: 'Build Hello World Java Project'
  
- stage: Verify
  steps:
  - script: |
        echo 'Listing files in the directory'
        ls
        pwd
        displayName: 'Verify Jar File'

- stage: Deploy
  steps:
  - script: |
        echo 'Executing the Hello World'
        ls 
        pwd 
        java -jar HelloWorld.jar
        displayName: 'Execute Hello World App'
