trigger:
- main

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: |
        echo "Building Hello World Java Project"
        javac HelloWorld.java
        jar cfm HelloWorld.jar Manifest.txt HelloWorld.class
      displayName: 'Build Hello World Java Project'
  
- stage: Verify
  jobs:
  - job: VerifyJob
    steps:
    - script: |
        echo 'Listing files in the directory'
        ls
      displayName: 'Verify Jar File'

- stage: Deploy
  jobs:
  - job: DeployJob
    steps:
    - script: |
        echo 'Executing the Hello World'
        java -jar HelloWorld.jar
      displayName: 'Execute Hello World App'
