trigger:
- main

stages:
- stage: Build and Run
  jobs:
  - job: Build and Run Job
    steps:
    - script: |
        echo "Building Hello World Java Project"
        javac HelloWorld.java
        jar cfm HelloWorld.jar Manifest.txt HelloWorld.class
        ls
        pwd
        java -jar HelloWorld.jar
      displayName: 'Build Hello World Java Project'
      
